kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: registry:5000/helloworld
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30300
  selector:
    app: helloworld